### ISSUE TITLE
Resolved: Underscores

### ISSUE THREAD

**Issue by briankirz** [David-Peede/mentee_research#12]
The bug that we saw this morning was a result of an input variable declaration including underscores to delineate thousandth places. For some reason, OSCAR doesn't recognize numbers with underscores.

![python3 size _](https://user-images.githubusercontent.com/38798045/180511226-d21f4e14-947f-4594-b3e0-e98677777d22.png)
![vim size _](https://user-images.githubusercontent.com/38798045/180511728-d96e9900-5f31-48ca-b6a5-19d3a8499b19.png)

Because I want the ease of just copying over updated versions of my files to OSCAR without having to worry about fixing it every time, I've removed these underscores on github so that instead of `50_000` and `20_000_000` we just have `50000` and `20000000`.

**Comment by David-Peede** [comment]
What was your python version @briankirz?

Here is a function I ran today on OSCAR with no issues...

```python
# Define IUA model of introgression.
def iua_human_model(admix_prop):
    # Intialize demographic model.
    iua_model = msprime.Demography()
    # We assume constant and equal effective population sizes for
    # all lineages.
    iua_model.add_population(name='AFR', initial_size=10_000)
    iua_model.add_population(name='EUR', initial_size=10_000)
    iua_model.add_population(name='NEA', initial_size=10_000)
    iua_model.add_population(name='AMH', initial_size=10_000)
    iua_model.add_population(name='HUM', initial_size=10_000)
    # Introgression from the Neanderthal to the Eurasian lineage
    # occuring 1,600 generations ago with a probability of f.
    iua_model.add_mass_migration(
        time=1_600, source='EUR', dest='NEA', proportion=admix_prop,
    )
    # The African and Eurasian lineages merge into the anatomically
    # modern human lineage 4,000 generations ago.
    iua_model.add_population_split(
        time=4_000, derived=['AFR', 'EUR'], ancestral='AMH',
    )
    # The anatomically modern human and Neanderthal lineages merge
    # into the ancestral human lineage 16,000 generations ago.
    iua_model.add_population_split(
        time=16_000, derived=['AMH', 'NEA'], ancestral='HUM',
    )
    return iua_model
```

**Comment by briankirz** [comment]
The single change of this
![python3 size _](https://user-images.githubusercontent.com/38798045/180560862-fa017614-79ce-47f7-8dfe-9dd766eecd26.png)
to this
![Screen Shot 2022-07-22 at 4 36 00 PM](https://user-images.githubusercontent.com/38798045/180560687-9d4f0407-2393-464a-ba99-f9cfcccd8ea4.png)
fixed the bug

The only difference I can see between my code and this is that my declared value is in the header vs as an argument to a function later on.

**Comment by David-Peede** [comment]
Hey @briankirz, you are correct that you fixed the bug—a lot of science is just being able to get things to work! However, the other part of science is learning, so at our next meeting, I would appreciate it if you told me exactly what causes this error—I gave you a hint earlier. Happy coding :)

**Comment by briankirz** [comment]
@David-Peede,
This could be so easy as to be trivial, but I know that the '_' option to delineate thousandths places was only introduced in python 3.6. When I execute code in the local terminal, it's running on python3. When I execute code in OSCAR, it's only running in python, and doesn't recognize python3.

<img width="331" alt="Screen Shot 2022-08-01 at 10 12 53 AM" src="https://user-images.githubusercontent.com/38798045/182177632-1050ca86-c846-4a4f-bdb0-5587ad9c8168.png">

To check this, I loaded the python 3 module in OSCAR. As you can see, I had been using python 2.7. I changed the `python` command in the job submission to `python3`, and it worked totally fine.

Thanks for reminding me about fixing problems vs understanding/learning. I'll do my best not to make that mistake again or put myself in a position where I'm so concerned about being pressed for time that I don't do my due diligence in understanding why a fix works.

**Comment by David-Peede** [comment]
Great @briankirz ! And as I said before, there is a time and place for quick fixes and getting code to run; just make sure you go back and understand why so we can learn something!
