### ISSUE TITLE
Prioritizing Performance Metrics

### ISSUE THREAD

**Issue by briankirz** [David-Peede/mentee_research#13]
As you remember, I calculated four performance indicators for each gamma matrix output of Baum-Welch:

- False Positive Rate
- False Negative Rate (Miss Rate):
- True Positive Rate (Sensitivity):
- True Negative Rate (Specificity):

<img width="504" alt="Screen Shot 2022-07-22 at 4 39 05 PM" src="https://user-images.githubusercontent.com/38798045/180562819-7034016f-c2ef-41df-b42c-d4c21000208a.png">
<img width="398" alt="Screen Shot 2022-07-22 at 4 39 13 PM" src="https://user-images.githubusercontent.com/38798045/180562922-5ffec323-1da7-46af-9f6e-0f642ababa5e.png">

I'd like to find and record which of the Baum-Welch iterations in a single rep perform the best, and what their indicators are. Should I prioritize one statistic (pick the version with the highest true positive rate)?. Or should I indicate the iteration that gives the best value for each metric independently?

**Comment by David-Peede** [comment]
You can look at doing something like a ROC curve, but I would just suggest generating some preliminary data to analyze first! You can also look at what others have done in the list of papers you have!
