### ISSUE TITLE
Processing VCF files

### ISSUE THREAD

**Issue by David-Peede** [David-Peede/mentee_research#4]
- [x] Make a directory `kirz_tutorials`
- [x] Make a subdirectory `vcf_processing`
- [x] Either copy over or download the chr1 TGP VCF file and the panel file from the shared data directory or from the online ftp
- [x] Copy over the chr1 index file `.tbi` or index it using [bgzip](http://www.htslib.org/doc/bgzip.html)
- [x] Filter the VCF file to only contain bi-allelic SNPs using [bcftools](https://samtools.github.io/bcftools/bcftools.html) (HINT: you don't need to download the program it is already a module on OSCAR)
- [x] Filter the VCF file the same way but this time treat it as a text file and do it in python
- [x] Make sure the VCF files are the same, if they're not figure out why
- [x] Submit a pull request with all your code but exclude the VCF files

**Comment by briankirz** [comment]
Copy over .panel file inside shared directory (data/data) and copy chr1 TGP vcf file (ends with .vcf.gz)
also do the .tbi one (have to have both .vcf.gz and .vcf.gz.tbi
Need the index of it, which is the .tbi

**Comment by briankirz** [comment]
also do the .tbi one (have to have both .vcf.gz and .vcf.gz.tbi
Need the index of it, which is the .tbi

**Comment by briankirz** [comment]
<img width="1424" alt="Screen Shot 2022-02-02 at 5 46 29 PM" src="https://user-images.githubusercontent.com/38798045/152250470-c31e2e6e-cc0c-4732-bc56-dd3b8696b931.png">
Use module loading whenever you want to use BCFtools

**Comment by briankirz** [comment]
Treat VCF as text file and do it in python: VCF file that I'm going to copy over is unfiltered, I'm only interested in Biallelic SNPs.

Same scheme two different ways:
1. BCFtools one line command to filter:
`bcftools view -m2 -M2 -v snps input.vcf.gz -o output.vcf.gz`

> WRONG: input/output need to be unzipped

3. One line command written by myself in python that should take an inputted VCF file and outputs a VCF file with outputted SNPS (currently outputs text file)
`python biallelic.py input.vcf.gz output.vcf`

**Comment by briankirz** [comment]
Find a way to compare python output and vcftools output, then submit the pull request when both are done

**Comment by briankirz** [comment]
'import sys
import gzip
import numpy as np

def biallelic(vcf_input, vcf_output):
        """
        Takes in input filepath and output filepath. Unzips the input,
        and returns a NumPy array.

        Read the data of the file into a buffer and use np.frombuffer
        to turn the data into a NumPy array.

        :param vcf_in: filepath for inputs, ex. 'ALL...vcf.gz'
        :param vcf_out: filepath for outputs, ex. 'vcf_out.gz'
        :return: NumPy array of vcf file
        """

        with gzip.open(vcf_input, 'rb') as f:
                print("starting...")
                lines = f.read()
                print("done reading...")
                line_list = lines.split('\n')
                print("done splitting...")

        vcf_size = len(line_list)
        print(line_list[0])
        for line in range(len(line_list)):
                print(line_list[line])

        with open(vcf_output, 'w') as f:
                header = True
                if line_list[-1]:
                        blank_end = 0
                else:
                        blank_end = 1
                for line in range(len(line_list)-blank_end):
                        if line % 100 == 0:
                                print("Running line " + str(line) + " out of " + str(vcf_size) + "...")


                        if header and (line_list[line][0] == "#"):
                                f.write(line_list[line])
                                f.write('\n')
                                if line_list[line+1][0] != "#":
                                        header = False
                        else:
                                alt = line_list[line].split('\t')[4]
                                if (len(alt) == 1) and (alt != "."):
                                        f.write(line_list[line])
                                        f.write('\n')
        print("Biallelic filtering complete")
        return None

biallelic(sys.argv[1], sys.argv[2])'

**Comment by briankirz** [comment]
`def biallelic(vcf_input, vcf_output):
        """
        Takes in input filepath and output filepath. Unzips the input,
        and returns a NumPy array.

        Read the data of the file into a buffer and use np.frombuffer
        to turn the data into a NumPy array.

        :param vcf_in: filepath for inputs, ex. 'ALL...vcf.gz'
        :param vcf_out: filepath for outputs, ex. 'vcf_out.gz'
        :return: NumPy array of vcf file
        """

        with gzip.open(vcf_input, 'rb') as f:
                print("starting...")
                lines = f.read()
                print("done reading...")
                line_list = lines.split('\n')
                print("done splitting...")

        vcf_size = len(line_list)
        print(line_list[0])
        for line in range(len(line_list)):
                print(line_list[line])

        with open(vcf_output, 'w') as f:
                header = True
                if line_list[-1]:
                        blank_end = 0
                else:
                        blank_end = 1
                for line in range(len(line_list)-blank_end):
                        if line % 100 == 0:
                                print("Running line " + str(line) + " out of " + str(vcf_size) + "...")


                        if header and (line_list[line][0] == "#"):
                                f.write(line_list[line])
                                f.write('\n')
                                if line_list[line+1][0] != "#":
                                        header = False
                        else:
                                alt = line_list[line].split('\t')[4]
                                if (len(alt) == 1) and (alt != "."):
                                        f.write(line_list[line])
                                        f.write('\n')
        print("Biallelic filtering complete")
        return None
`

**Comment by briankirz** [comment]
Current code works fine on Y chromosome with manual test cases passed. Will not move past f.read() for large c1 file. Possible that it asks too much of memory allocation. Will try different strategy

**Comment by briankirz** [comment]
Found the problem: I was doing

```
with gzip.open(vcf_input, 'rb') as f:
                lines = f.read()
                line_list = lines.split('\n')
```

when I should have been doing `for line in f`

**Comment by briankirz** [comment]
Size of chr1 is approx. 6.5 million lines. Completed in ~10 mins. Wrote output to text file.

**Comment by briankirz** [comment]
Fixing bcftools command. I had:
`bcftools view -m2 -M2 -v snps input.vcf.gz -o output.vcf.gz`
Gives error:
`[W::vcf_parse] Contig 'Y' is not defined in the header. (Quick workaround: index the file withtabix.)`

Not sure how I didn't get this error the first time:
Edit, it seems to be unique to Y-chrom and doesn't affect functionality

SOLUTION: I was reading and writing to a .gz file when I should have been r/w to a .vcf file
`bcftools view -m2 -M2 -v snps input.vcf.gz -o output.vcf`

Taught myself really really useful shortcut
`gzip -d input.vcf.gz` to decompress, `gzip input.vcf.gz` to recompress

Now I can compare!

**Comment by briankirz** [comment]
Hit a snag in comparison: files seem to be the same except BCFtools has 
`##FILTER=<ID=PASS,Description="All filters passed">` so I get rid of it by skipping line 2

**Comment by briankirz** [comment]
SOLUTION OVERVIEW:

NECESSARY FILES:
> chr.vcf.gz
> biallelic.py
> compare_vcf.py

STEPS:
`python biallelic.py chr.vcf.gz my_chr.vcf` (6.5 million lines, ~5 min)
`bcftools view -m2 -M2 -v snps chr.vcf.gz -o bcf_chr.vcf` (similar runtime, maybe longer)
- Make sure to include -Oz to make sure bcftools outputs a gzipped vcf
- Include vt = SNP condition in this one-liner

`python compare_vcf.py my_chr.vcf bcf_chr.vcf` (order matters!)
- annotate biallelic.py


returns `True`, indicating bcftools and biallelic.py outputs are identical!

**Comment by briankirz** [comment]
OSCAR Reading:

Submitting Jobs subsection on left
Software on left

Include won't work - update bcftools to 1.3

Using a python function, write file where 
First column is chromosome number (ie, 1,2,3 NOT chr123), second column is position of indel

Push:
Python code that created the files
Files themselves
submit shell code

**Comment by David-Peede** [comment]
- [x] Compare the `bcftools view -m2 -M2 -v snps` vs `bcftools -m2 -M2 -i 'INFO/VT="SNP"'` outputs.
- [x] Quantify and record the number of different sites between the two outputs.

You can use this SLURM script as an example but make sure you change the output file names, path names, and my email:
```bash
#!/bin/bash
#
#SBATCH -J tgp_filter         # Job name
#SBATCH -N 1                                    # Number of cores
#SBATCH -n 4                      #Ensure that all cores are on one machine
#SBATCH -t 6:00:00              # Runtime in D-HH:MM (or use minutes)
#SBATCH --mem 4g             # Memory in MB
#SBATCH -o logs/tgp_filter-%A.out # File for STDOUT (with jobid = %j)
#SBATCH -e logs/tgp_filter-%A.err          # File for STDERR (with jobid = %j)
#SBATCH --mail-type=ALL          # Type of email notification: BEGIN,END,FAIL,A$
#SBATCH --mail-user=david_peede@brown.edu  #Email where notifications will be sent


module load bcftools/1.13 gsl/2.5 gcc/8.3 perl/5.24.1

for CHR in {1..22}; do
bcftools view -m2 -M2 -i 'INFO/VT="SNP"' -Oz -o tgp_biallelic_snps_chr${CHR}.vcf.gz /users/dpeede/data/data/modern_genomes/1000genomes/ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr${CHR}.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz
done
```

**Comment by briankirz** [comment]
Quick clarifying question: when comparing the differences between the text files I’ve generated by extracting indels using both -v and -i bcftools commands, I know I should be using the format 
CHROM | Version (-v or -i) | POS

Should I be making separate text files each chromosome comparison, or compile every chromosome comparison into one output file with all of the differences in it? I'm defaulting to the former for the time being as it's much simpler to code

**Comment by David-Peede** [comment]
Always be parallelizing—by chromosome!

**Comment by briankirz** [comment]
Okay, I pushed the cluster files to Github and committed the changes to the Processing-VCF-files branch

**Comment by David-Peede** [comment]
Make sure to submit a pull request when you are done with everything!
